45、JAVA 语言如何进行异常处理，关键字：throws,throw,try,catch,finally 分别代表什么意义？在 try 块中可以抛出异常吗？
throws 捕获并向外抛出异常
throw 抛出异常
try catch 是内部捕获异常并做自定义处理
finally 是无论是否有异常都会被处理的语句，除非在 finally 前存在被执行的
System.exit(int i)时除外






答：Java 通过面向对象的方法进行异常处理，把各种不同的异常进行分类，并提供了良好的接 口。在 Java 中，每个异常都是一个对象，它是 Throwable 类或其它子类的实例。当一个方法出 现异常后便抛出一个异常对象，该对象中包含有异常信息，调用这个对象的方法可以捕获到这个 异常并进行处理。Java 的异常处理是通过 5 个关键词来实现的：try、catch、throw、throws 和 finally。一般情况下是用 try 来执行一段程序，如果出现异常，系统会抛出（throws）一个 异常，这时候你可以通过它的类型来捕捉（catch）它，或最后（finally）由缺省处理器来处理。 用 try 来指定一块预防所有"异常"的程序。紧跟在 try 程序后面，应包含一个 catch 子句来指定 你想要捕捉的"异常"的类型。
throw 语句用来明确地抛出一个"异常"。
throws 用来标明一个成员函数可能抛出的各种"异常"。
Finally 为确保一段代码不管发生什么"异常"都被执行一段代码。 可以在一个成员函数调用的外面写一个 try 语句，在这个成员函数内部写另一个 try 语句保护其 他代码。每当遇到一个 try 语句，"异常"的框架就放到堆栈上面，直到所有的 try 语句都完成。 如果下一级的 try 语句没有对某种"异常"进行处理，堆栈就会展开，直到遇到有处理这种"异常" 的 try 语句。